In [ ]:
import numpy as np


empty_array = np.empty((2, 2))
print("Empty array (2x2):")
print(empty_array)


ones_array = np.ones((4, 2))
print("\nAll-one array (4x2):")
print(ones_array)


full_array = np.full((3, 3), 7)
print("\nFull array (3x3 filled with 7):")
print(full_array)


given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros like given array:")
print(zeros_like_array)


ones_like_array = np.ones_like(given_array)
print("\nOnes like given array:")
print(ones_like_array)


new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted numpy array:")
print(numpy_array)


Empty array (2x2):
[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

All-one array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array (3x3 filled with 7):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like given array:
[[0 0]
 [0 0]]

Ones like given array:
[[1 1]
 [1 1]]

Converted numpy array:
[1 2 3 4]


In [ ]:
import numpy as np

arr_10_49 = np.arange(10, 50)
matrix_0_8 = np.arange(9).reshape(3, 3)
identity_matrix = np.eye(3)
random_30 = np.random.random(30)
mean_random_30 = random_30.mean()
random_10_10 = np.random.random((10, 10))
min_value = random_10_10.min()
max_value = random_10_10.max()
zero_array = np.zeros(10); zero_array[4] = 1
arr = np.array([1,2,0,0,4,0]); reversed_arr = arr[::-1]
border_array = np.ones((5, 5)); border_array[1:-1, 1:-1] = 0
checkerboard = np.zeros((8, 8)); checkerboard[1::2, ::2] = 1; checkerboard[::2, 1::2] = 1

print(arr_10_49)
print(matrix_0_8)
print(identity_matrix)
print(mean_random_30)
print(min_value, max_value)
print(zero_array)
print(reversed_arr)
print(border_array)
print(checkerboard)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
0.4968659891722022
0.0045163774103405 0.9809998283654455
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

add_xy = x + y
sub_xy = x - y
mul_x = x * 3
square_x = x ** 2

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))

try:
    concat_xv = np.concatenate((x, v))
except Exception as e:
    concat_xv = str(e)

print(add_xy)
print(sub_xy)
print(mul_x)
print(square_x)
print(dot_vw)
print(dot_xv)
print(dot_xy)
print(concat_xy_row)
print(concat_vw_col)
print(concat_xv)


[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
import numpy as np


A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)


AB = np.dot(A, B)
BA = np.dot(B, A)
AB_not_BA = not np.allclose(AB, BA)


AB_T = (AB).T
B_T_A_T = np.dot(B.T, A.T)
transpose_equal = np.allclose(AB_T, B_T_A_T)

print("A * A^-1 = \n", I)
print("\nAB = \n", AB)
print("BA = \n", BA)
print("AB != BA: ", AB_not_BA)
print("\n(AB)^T = \n", AB_T)
print("B^T A^T = \n", B_T_A_T)
print("Transpose equality: ", transpose_equal)

# Solve system of linear equations using inverse method
# Equations:
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

# Coefficient matrix
coeff_matrix = np.array([[2, -3, 1],
                         [1, -1, 2],
                         [3, 1, -1]])

# Constant matrix
const_matrix = np.array([-1, -3, 9])

# Solution using inverse
solution = np.dot(np.linalg.inv(coeff_matrix), const_matrix)
print("\nSolution using inverse method:", solution)


A * A^-1 = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
AB != BA:  True

(AB)^T = 
 [[23 51]
 [13 29]]
B^T A^T = 
 [[23 51]
 [13 29]]
Transpose equality:  True

Solution using inverse method: [ 2.  1. -2.]


In [ ]:
import numpy as np
import time

# -----------------------------
# Element-wise Addition
# -----------------------------
size = 1_000_000

# Using Python lists
list1 = list(range(size))
list2 = list(range(size))
start = time.time()
list_add = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print("Python list addition time:", end - start, "seconds")

# Using NumPy arrays
arr1 = np.arange(size)
arr2 = np.arange(size)
start = time.time()
arr_add = arr1 + arr2
end = time.time()
print("NumPy array addition time:", end - start, "seconds")

# -----------------------------
# Element-wise Multiplication
# -----------------------------
# Python lists
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print("Python list multiplication time:", end - start, "seconds")

# NumPy arrays
start = time.time()
arr_mul = arr1 * arr2
end = time.time()
print("NumPy array multiplication time:", end - start, "seconds")

# -----------------------------
# Dot Product
# -----------------------------
# Python lists
start = time.time()
dot_list = sum([list1[i] * list2[i] for i in range(size)])
end = time.time()
print("Python list dot product time:", end - start, "seconds")

# NumPy arrays
start = time.time()
dot_array = np.dot(arr1, arr2)
end = time.time()
print("NumPy dot product time:", end - start, "seconds")

# -----------------------------
# Matrix Multiplication (1000x1000)
# -----------------------------
matrix_size = 1000

# Python lists
matrix1 = [[i+j for j in range(matrix_size)] for i in range(matrix_size)]
matrix2 = [[i-j for j in range(matrix_size)] for i in range(matrix_size)]

start = time.time()
result = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(matrix_size))
           for j in range(matrix_size)] for i in range(matrix_size)]
end = time.time()
print("Python list matrix multiplication time:", end - start, "seconds")

# NumPy arrays
matrix1_np = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
matrix2_np = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

start = time.time()
result_np = np.dot(matrix1_np, matrix2_np)
end = time.time()
print("NumPy matrix multiplication time:", end - start, "seconds")


Python list addition time: 0.11180734634399414 seconds
NumPy array addition time: 0.0036704540252685547 seconds
Python list multiplication time: 0.10651946067810059 seconds
NumPy array multiplication time: 0.004163265228271484 seconds
Python list dot product time: 0.13782811164855957 seconds
NumPy dot product time: 0.0023953914642333984 seconds
Python list matrix multiplication time: 184.3474464416504 seconds
NumPy matrix multiplication time: 1.6477677822113037 seconds
